// Every automation in the tool, as data. The wireframe screen renders this
// and writes back to it, so the diagram cannot drift from the behaviour.
// t = trigger · c = conditions · a = actions · n = notifies · g = guard
// s = live | blocked | off · w = why it is blocked
window.CRUX_AUTO = [
// ---------------------------------------------------------------- scheduled
{id:'J01',d:'Scheduled jobs',n:'Outbox worker',own:'Technology',s:'live',
 t:['Every 5 minutes'],
 c:['Rows in notification_outbox with status QUEUED','Today\u2019s mail budget not exhausted','Attempt count under the ladder cap'],
 a:['Claim a batch under an advisory lock','Send through the channel adapter','Write delivery row with the idempotency key'],
 nt:['Nobody — this job is plumbing'],
 g:'One unique idempotency key per send. A second worker claiming the same row is refused by the lock, which is the defect that produced 1,892 sends from 77 keys.'},
{id:'J02',d:'Scheduled jobs',n:'Monthly matrix dispatch',own:'Operations',s:'live',
 t:['1st of the month, 09:00'],
 c:['Client active for the month','Branch matrix complete at all five levels','No dispatch row already sent for this month marker'],
 a:['Build one dispatch row per branch','Queue to the outbox with month-keyed idempotency'],
 nt:['Client contact ladder levels 1\u20135','Branch Manager on failure'],
 g:'A branch with an incomplete matrix is held out, not sent to. Held branches are listed with their reason rather than silently skipped.'},
{id:'J03',d:'Scheduled jobs',n:'Escalation chase',own:'Operations',s:'live',
 t:['Hourly, 10:00\u201317:00 business hours'],
 c:['Escalation open past its level TAT','Next level exists in the matrix'],
 a:['Raise the next escalation level','Write ESCALATED with a level-scoped idempotency key'],
 nt:['Next level holder','Assignor and assignee'],
 g:'hash(assignment, cycle, level, trigger) is unique, so a re-run cannot double-escalate.'},
{id:'J04',d:'Scheduled jobs',n:'Matrix completeness chase',own:'Operations',s:'live',
 t:['Monday 11:00'],
 c:['Branch matrix missing any level','Branch active for a live client'],
 a:['Write the gap to the branch record','Start or continue the P-06 14-day clock'],
 nt:['Branch Manager','Regional Manager at day 10'],
 g:'The clock is per branch and per level, so fixing one level does not reset the others.'},
{id:'J05',d:'Scheduled jobs',n:'Penalty sweep',own:'Finance',s:'blocked',
 t:['Nightly 00:05'],
 c:['Penalty rule active','Cutoff passed','No instance already raised for this rule and period'],
 a:['Raise a penalty instance at the amount in force on the cutoff date','Post to the ledger'],
 nt:['Person penalised','HR for payroll rules, Finance for P-06'],
 g:'Amount is captured at raise time. Changing a rule later never restates a penalty already raised.',
 w:'Four penalty amounts are still placeholders. The sweep runs and reports but will not post until they are finalised.'},
{id:'J06',d:'Scheduled jobs',n:'Daily count lock',own:'Business Excellence',s:'live',
 t:['23:59 daily'],
 c:['Person files a daily count','Count not yet submitted'],
 a:['Lock the day','Mark it missed if empty'],
 nt:['Reporting manager on a miss'],
 g:'A locked day can only be reopened by HR with a reason, so the count cannot be back-filled quietly.'},
{id:'J07',d:'Scheduled jobs',n:'Auto-close sweep',own:'Operations',s:'live',
 t:['Nightly 00:10'],
 c:['Escalation resolved and acknowledged','No request pending','7 days since resolution'],
 a:['Close the escalation','Stop every clock'],
 nt:['Raiser'],
 g:'Refuses to close while any requirement is incomplete or any request is open.'},
{id:'J08',d:'Scheduled jobs',n:'Monthly summary pack',own:'Business Excellence',s:'live',
 t:['10th of the month'],
 c:['Month closed','Targets exist for the month'],
 a:['Assemble target vs achieved per person','Attach attributes and FYI notes','Publish the review pack'],
 nt:['Every chair holder and their manager'],
 g:'Reads the roll-up, never the transaction tables, so a review pack cannot slow the tool at month end.'},
{id:'J09',d:'Scheduled jobs',n:'Appreciation nudge',own:'Human Resources',s:'live',
 t:['Monday 09:30'],
 c:['A person met target every day last week','No appreciation sent in 30 days'],
 a:['Draft an appreciation note for the manager to send'],
 nt:['Reporting manager, not the person'],
 g:'Drafted, never auto-sent. Praise from a robot is worth nothing.'},
{id:'J10',d:'Scheduled jobs',n:'Note classification',own:'Business Excellence',s:'live',
 t:['Nightly, after the daily lock'],
 c:['Open notes filed today','Note is not empty'],
 a:['Classify as an Attribute with a heading, or as FYI','File into the monthly review'],
 nt:['Author, so they can correct the filing'],
 g:'The author can always overrule the classification, and the original text is kept verbatim beside it.'},
{id:'J11',d:'Scheduled jobs',n:'Roll-up rebuild',own:'MIS',s:'live',
 t:['Nightly 01:00'],
 c:['Yesterday closed'],
 a:['Rebuild KPI roll-ups per chair, branch, region and company'],
 nt:['MIS on a variance'],
 g:'Reconciles to source counts and refuses to publish on a variance, rather than publishing a wrong number.'},
{id:'J12',d:'Scheduled jobs',n:'Claim reminder',own:'Finance',s:'live',
 t:['Daily 10:00'],
 c:['Claim submitted and unapproved past 3 days'],
 a:['Remind the approver'],
 nt:['Approver, then their manager at day 7'],
 g:'Escalates once, then stops. A reminder loop is what filled the old audit log with noise.'},

// ---------------------------------------------------------------- OGL
{id:'O01',d:'OGL workflow',n:'TAT resolution and snapshot',own:'Operations',s:'blocked',
 t:['Assignment submitted'],
 c:['Client, verification type, geography and quantity known','A matching SLA rule exists'],
 a:['Score every matching rule by specificity','Snapshot the winning TAT onto the instance','Write the full rule trace including runners-up'],
 nt:['Assignor sees the resolved TAT before assigning'],
 g:'Snapshotted. A rule change later never moves a clock that is already running.',
 w:'Holiday calendars are empty. No TAT may be enforced until holidays are loaded for this and next financial year.'},
{id:'O02',d:'OGL workflow',n:'SLA status tick',own:'Operations',s:'live',
 t:['Every 5 minutes'],
 c:['Instance open','Elapsed business minutes crossed 75% or 100%'],
 a:['Set AT_RISK, then BREACHED','Write SLA_AT_RISK / SLA_BREACHED'],
 nt:['Next action owner','Assignor at breach'],
 g:'sla_status is an attribute, not a state. A breached assignment still shows its operator the correct next action.'},
{id:'O03',d:'OGL workflow',n:'Clock segment ledger',own:'Operations',s:'live',
 t:['Any state change on an assignment'],
 c:['An instance exists'],
 a:['Close the open segment with its business minutes','Open a new segment with state and attribution'],
 nt:['Nobody — the ledger is the record'],
 g:'A partial unique index allows exactly one open segment per instance, so overlap is impossible rather than unlikely.'},
{id:'O04',d:'OGL workflow',n:'RFI conditional pause',own:'Operations',s:'live',
 t:['RFI raised'],
 c:['Consumed under 50% of TAT','No pause already granted this cycle','Reason is in the pause-eligible set'],
 a:['Credit up to 120 business minutes','Open a PAUSED segment attributed to the assignor'],
 nt:['Assignee sees the decision and its arithmetic before submitting'],
 g:'Shown before submission, so a pause is never a surprise and never a free extension.'},
{id:'O05',d:'OGL workflow',n:'Sub-TAT timers',own:'Operations',s:'live',
 t:['Request raised'],
 c:['RFI 2 hours, delay 1 hour'],
 a:['Start the sub-TAT','Mark it breached on expiry'],
 nt:['Assignor, then their manager on breach'],
 g:'A sub-TAT breach escalates on the assignor side, so no strike can land on the assignee for that cycle.'},
{id:'O06',d:'OGL workflow',n:'Delay auto-accept',own:'Operations',s:'live',
 t:['Delay sub-TAT expires unreviewed'],
 c:['No auto-accept already used on this assignment'],
 a:['Resolve AUTO_ACCEPTED','Attribute the minutes PENDING_REVIEW','Cap the extension at due + 12 business hours'],
 nt:['Assignor and their manager','Adds to the Confirm Attribution tray'],
 g:'One auto-accept only. A second unreviewed delay escalates instead of self-approving, so silence never becomes a renewable extension.'},
{id:'O07',d:'OGL workflow',n:'Escalation ladder L1\u2013L4',own:'Operations',s:'live',
 t:['Breach, sub-TAT breach, or a manual raise'],
 c:['Level exists','No instance with the same idempotency key'],
 a:['Resolve the recipient','Insert the escalation','Hand to the outbox'],
 nt:['Level holder','Both sides of the assignment'],
 g:'One adapter, one key. No routing logic lives inside the assignment workflow.'},
{id:'O08',d:'OGL workflow',n:'Hierarchy fallback',own:'Operations',s:'live',
 t:['Escalation recipient not found in the matrix'],
 c:['Exact, then client+location, then location keys all missed'],
 a:['Walk the assignee location\u2019s org hierarchy','Deliver anyway','Write ESCALATION_FALLBACK_USED'],
 nt:['Resolved recipient'],
 g:'Never drops an escalation because configuration is incomplete.'},
{id:'O09',d:'OGL workflow',n:'CONFIG_GAP alert',own:'Technology',s:'live',
 t:['Fallback used'],
 c:['A matrix key was genuinely missing'],
 a:['Raise a CONFIG_GAP naming the exact missing key'],
 nt:['Administrator and Operations Head'],
 g:'Names the key rather than saying \u201cescalation failed\u201d, so the gap is fixable in one action.'},
{id:'O10',d:'OGL workflow',n:'Strike generation',own:'Human Resources',s:'live',
 t:['Nightly sweep under an advisory lock'],
 c:['Instance breached past grace','Assignee-attributed minutes exceed the TAT','No PENDING_REVIEW segment unresolved on that cycle'],
 a:['Insert a strike_event with the location as at breach time'],
 nt:['Person struck','Their manager and HR'],
 g:'Unique on (assignment, cycle, trigger). The same sweep running twice cannot produce a second strike.'},
{id:'O11',d:'OGL workflow',n:'Strike waiver',own:'Human Resources',s:'live',
 t:['Dispute classified NOT_UPHELD'],
 c:['A strike exists on that cycle'],
 a:['Set status WAIVED with a reason','Count the failure on the assignor quality KPI'],
 nt:['Person, their manager, HR'],
 g:'Waived, never deleted. The row stays visible as waived so the history is honest.'},
{id:'O12',d:'OGL workflow',n:'Priority score recompute',own:'Operations',s:'live',
 t:['Every 10 minutes, and on any state change'],
 c:['Assignment open'],
 a:['Recompute age, SLA pressure, escalation level, client tier and rework penalty','Bucket as Breach, Attention or Normal'],
 nt:['Nobody — it reorders the queue'],
 g:'Operators read the bucket; the number only orders. A score nobody can explain is not a priority.'},
{id:'O13',d:'OGL workflow',n:'Control tower refresh',own:'MIS',s:'live',
 t:['Every 5 minutes'],
 c:['Summary view stale'],
 a:['Refresh the materialised assignment summary'],
 nt:['Nobody'],
 g:'The tower reads the summary, never the transaction tables. Twelve live counts on every dashboard load is how you take the system down at 09:30.'},
{id:'O14',d:'OGL workflow',n:'Repeat Point ID triage',own:'Operations',s:'live',
 t:['A Point ID already on record is keyed again'],
 c:['A prior attempt exists','Address compared and scored'],
 a:['Write a decision row with the system\u2019s proposal','Hold the assignment in DRAFT with no clock'],
 nt:['Assignor only \u2014 never the assignee'],
 g:'Proposes, never applies. Undecided repeats are a queue with an owner rather than a silent backlog.'},
{id:'O15',d:'OGL workflow',n:'Duplicate check',own:'Operations',s:'live',
 t:['Assignment submitted'],
 c:['Live attempt on the same point, or a fuzzy name-address-pincode match'],
 a:['Refuse a second live assignment','Warn on a fuzzy match and require a reason'],
 nt:['Assignor'],
 g:'An override is a row with an author and a reason, replacing the hand-maintained duplicate column.'},
{id:'O16',d:'OGL workflow',n:'Arbitration trigger',own:'Operations',s:'live',
 t:['Third dispute attempt'],
 c:['Two disputes already raised'],
 a:['Open arbitration with the lowest common manager','Lock both parties out of further disputes'],
 nt:['Both parties and the arbiter'],
 g:'The arbiter is computed from the closure table, so it cannot be chosen to suit either side.'},

// ---------------------------------------------------------------- notification
{id:'N01',d:'Notification',n:'Mail budget guard',own:'Technology',s:'live',
 t:['Before every send'],
 c:['Daily sends under 1,800','200 reserved for escalations'],
 a:['Send, or hold in the outbox with a reason'],
 nt:['Administrator when the reserve is touched'],
 g:'1,849 of the old system\u2019s failures were quota exhaustion. The budget is a rule, not a hope.'},
{id:'N02',d:'Notification',n:'Retry ladder',own:'Technology',s:'live',
 t:['Delivery failure'],
 c:['Attempt under the cap','Failure is retryable'],
 a:['Retry under a NEW idempotency key','Leave the old key failed in the ledger'],
 nt:['Administrator after the final attempt'],
 g:'History shows one failure and one retry, never two sends.'},
{id:'N03',d:'Notification',n:'Bounce flagging',own:'Operations',s:'live',
 t:['Hard bounce'],
 c:['Recipient is a client or branch contact'],
 a:['Flag the contact on the branch record','Add a confirm-this-contact task to the next visit'],
 nt:['Branch Manager'],
 g:'A bad address becomes fieldwork rather than a repeating failure.'},
{id:'N04',d:'Notification',n:'Strike-3 warning ladder',own:'Human Resources',s:'live',
 t:['Third active strike inside the rolling 90 days'],
 c:['No strike waived below three','Facts assembled'],
 a:['Generate the warning with its facts','Require acknowledgement'],
 nt:['Person, manager, HR'],
 g:'The window is rolling and computed from events, so a strike ages out rather than being deleted.'},

// ---------------------------------------------------------------- PMS
{id:'P01',d:'Performance',n:'Daily count reminder and lock',own:'Business Excellence',s:'live',
 t:['17:30, then 23:59'],
 c:['Person files a count','Not yet submitted'],
 a:['Remind, then lock the day'],
 nt:['Person, then their manager'],
 g:'One reminder and one lock. Not a loop.'},
{id:'P02',d:'Performance',n:'Target vs achieved roll-up',own:'MIS',s:'live',
 t:['On submission, and nightly'],
 c:['Targets exist for the month'],
 a:['Compute achieved and percentage per KPI','Roll up the chain'],
 nt:['Chair holder and manager'],
 g:'Percentages are derived, never stored, so a corrected count corrects the roll-up.'},
{id:'P03',d:'Performance',n:'AI note filing',own:'Business Excellence',s:'live',
 t:['Note saved'],
 c:['Note has content'],
 a:['File as an Attribute with a heading, or as FYI','Show the source note beside it'],
 nt:['Author'],
 g:'The author can always overrule it, and the original wording is never rewritten.'},
{id:'P04',d:'Performance',n:'Monthly review assembly',own:'Human Resources',s:'live',
 t:['Month close'],
 c:['Attributes and counts present'],
 a:['Assemble the review pack per person'],
 nt:['Person and manager'],
 g:'No individual is scored by a machine. The pack is evidence for a conversation.'},

// ---------------------------------------------------------------- penalty
{id:'X01',d:'Penalty',n:'Rule application on cutoff',own:'Finance',s:'blocked',
 t:['Cutoff reached'],
 c:['Rule active','Condition still true at cutoff'],
 a:['Raise an instance at the amount in force'],
 nt:['Person and the recovering function'],
 g:'Amount captured at raise time.',
 w:'Awaiting the four final amounts.'},
{id:'X02',d:'Penalty',n:'P-06 matrix clock',own:'Operations',s:'live',
 t:['Matrix found incomplete'],
 c:['14 days elapsed and still incomplete'],
 a:['Raise the P-06 instance'],
 nt:['Branch Manager, Regional Manager, Finance'],
 g:'The clock is visible on the branch from day one, with days elapsed shown, so nobody is surprised at day 14.'},
{id:'X03',d:'Penalty',n:'Recovery routing',own:'Finance',s:'live',
 t:['Penalty instance raised'],
 c:['Rule is payroll or Finance recoverable'],
 a:['Route P-01 to P-05 and P-07 to HR payroll','Route P-06 to Finance'],
 nt:['Recovering function'],
 g:'One route per rule. A penalty cannot be recovered twice.'},

// ---------------------------------------------------------------- visits
{id:'V01',d:'Visits',n:'Branch record write-back',own:'Operations',s:'live',
 t:['Visit submitted'],
 c:['Visit has contact or finding data'],
 a:['Update branch manager and POC details','Append findings and pending issues'],
 nt:['Branch Manager'],
 g:'The visit is the source of truth for contacts, which is what keeps the matrix current without a data-entry task.'},
{id:'V02',d:'Visits',n:'RAG and ageing',own:'Operations',s:'live',
 t:['Visit submitted, and nightly'],
 c:['Next-visit date set'],
 a:['Recompute the branch RAG and ageing chip','State the reason for the colour'],
 nt:['Branch Manager and Regional Manager'],
 g:'A colour with no reason beside it is decoration. The reason is always rendered.'},
{id:'V03',d:'Visits',n:'Collection commitment to FMEA',own:'Finance',s:'live',
 t:['Collection commitment date passes'],
 c:['Amount not received'],
 a:['Write a missed-commitment FMEA line against the client'],
 nt:['Branch Manager and Credit & Collections'],
 g:'The commitment is captured at the visit, so the miss is evidenced rather than argued.'},
{id:'V04',d:'Visits',n:'Satisfaction 1 raises an escalation',own:'Operations',s:'live',
 t:['Visit records satisfaction 1'],
 c:['Always'],
 a:['Raise a service escalation automatically'],
 nt:['Branch Manager, Regional Manager, Business Development'],
 g:'A very dissatisfied client cannot be recorded and left alone.'},

// ---------------------------------------------------------------- org / HR
{id:'H01',d:'Org and people',n:'Chair KPI inheritance',own:'Human Resources',s:'live',
 t:['Chair KPI added or changed'],
 c:['Effective-dated from the next cadence period'],
 a:['Apply to everyone holding the chair','Leave the current period untouched'],
 nt:['Chair holders and their managers'],
 g:'Nobody is re-scored against a rule that moved mid-month.'},
{id:'H02',d:'Org and people',n:'Closure table rebuild',own:'Technology',s:'live',
 t:['Reporting line or chair changed'],
 c:['The move does not create a cycle'],
 a:['Rebuild org_unit_closure in the same transaction'],
 nt:['Both managers'],
 g:'My-team scope, escalation fallback and arbitration all read the new line immediately, so the three cannot disagree.'},
{id:'H03',d:'Org and people',n:'Vacancy surfacing',own:'Human Resources',s:'live',
 t:['A holder leaves or a chair is created'],
 c:['No active holder'],
 a:['Mark the chair vacant with its owned processes named'],
 nt:['HR and the parent chair'],
 g:'Unowned processes are shown rather than hidden, because a hidden vacancy is how work goes unowned.'},

// ---------------------------------------------------------------- upload
{id:'U01',d:'Bulk upload',n:'Validate, preview, apply',own:'Administrator',s:'live',
 t:['File uploaded'],
 c:['Same four validation levels as manual entry','No error rows if all-or-nothing chosen'],
 a:['Validate every row','Show valid, warning and error counts with the first 50 errors','Apply in one transaction'],
 nt:['Uploader'],
 g:'Nothing is relaxed for a file. That is how the old datastore acquired 198,890 empty rows.'},
{id:'U02',d:'Bulk upload',n:'Dependency order',own:'Administrator',s:'live',
 t:['Upload requested'],
 c:['Prerequisite masters loaded'],
 a:['Refuse with the missing dependency named'],
 nt:['Uploader'],
 g:'Refused whole rather than half-applied.'},
{id:'U03',d:'Bulk upload',n:'Rollback snapshot',own:'Administrator',s:'live',
 t:['Scope-replacing upload applied'],
 c:['Within 7 days'],
 a:['Keep a snapshot','Allow a one-action reversal with a reason'],
 nt:['Uploader and Administrator'],
 g:'A reversal is a new event that supersedes the upload, so the history shows both.'}
];
